import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { gzipSync, constants as zlibConstants } from 'node:zlib'
import { execFileSync } from 'node:child_process'

import { build } from 'esbuild'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = join(HERE, 'src')
const HEADER = join(HERE, '..', 'receiver', 'signal_store.h')

function gitHash() {
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: HERE, encoding: 'utf8' }).trim()
  } catch { return 'unknown' }
}

export async function deviceMax() {
  const src = await readFile(HEADER, 'utf8')
  const m = src.match(/^#define\s+SIGNAL_DEVICE_SLOTS\s+(\d+)/m)
  if (!m) throw new Error(`no SIGNAL_DEVICE_SLOTS in ${HEADER}`)
  return Number(m[1])
}

async function bundle(entry, loader, define) {
  const out = await build({
    entryPoints: [join(SRC, entry)],
    // PlatformIO runs this from receiver/, where there is no node_modules.
    // esbuild resolves alias targets against the working directory, so anchor
    // it here rather than wherever the caller happened to be.
    absWorkingDir: HERE,
    bundle: true,
    write: false,
    minify: true,
    // Otherwise esbuild keeps /*! ... */ license banners (e.g. @capacitor/core's)
    // inline, and the built page is meant to carry no such text.
    legalComments: 'none',
    format: 'iife',
    target: 'es2022',
    loader,
    define,
    jsx: 'automatic',
    jsxImportSource: 'preact',
    // pigeon-maps is a React component and declares react as its only peer.
    alias: { react: 'preact/compat', 'react-dom': 'preact/compat' },
  })
  return out.outputFiles[0].text
}

export async function buildHtml() {
  const define = { 
    DEVICE_MAX: String(await deviceMax()),
    GIT_HASH: JSON.stringify(gitHash())
  }
  const [template, css, js] = await Promise.all([
    readFile(join(SRC, 'index.html'), 'utf8'),
    bundle('style.css', {}, {}),
    bundle('main.jsx', { '.jsx': 'jsx' }, define),
  ])
  return template.replace('/*CSS*/', () => css.trim()).replace('/*JS*/', () => js.trim())
}

export async function writeProgmem(path) {
  const html = await buildHtml()
  const raw = Buffer.from(html, 'utf8')
  const gz = gzipSync(raw, { level: zlibConstants.Z_BEST_COMPRESSION })
  const rows = []
  for (let at = 0; at < gz.length; at += 16) {
    rows.push('  ' + [...gz.subarray(at, at + 16)].map((b) => `0x${b.toString(16).padStart(2, '0')}`).join(', '))
  }
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, [
    '#pragma once',
    '',
    '// Generated by dashboard/build.js. Not checked in.',
    '',
    '#include <Arduino.h>',
    '',
    'static const unsigned char DASHBOARD_HTML_GZ[] PROGMEM = {',
    rows.join(',\n'),
    '};',
    '',
    `static const size_t DASHBOARD_HTML_GZ_LEN = ${gz.length};`,
    '',
  ].join('\n'))
  return { raw: raw.length, gz: gz.length }
}

async function main() {
  const html = await buildHtml()
  const dist = join(HERE, 'dist')
  await mkdir(dist, { recursive: true })
  await writeFile(join(dist, 'index.html'), html)
  process.stderr.write(`dist/index.html ${html.length} bytes\n`)

  const at = process.argv.indexOf('--progmem')
  if (at >= 0) {
    const path = process.argv[at + 1]
    if (!path) throw new Error('--progmem needs a path')
    const { raw, gz } = await writeProgmem(path)
    process.stderr.write(`${path} ${gz} bytes gzipped from ${raw}\n`)
  }

  if (process.argv.includes('--bridge-public')) {
    const out = join(HERE, '..', 'bridge', 'public', 'index.html')
    await mkdir(dirname(out), { recursive: true })
    await writeFile(out, html)
    process.stderr.write(`${out} ${html.length} bytes\n`)
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main()
