export DEPLOY_TYPES="letsencrypt apache node_app"
export APP_NAME="mqtt-http-bridge"
export DOMAIN_NAME="weather.rkroll.com"
export REMOTE_HOST="weather.rkroll.com"
export REMOTE_USER="john"

export LETSENCRYPT_EMAIL="john@rkroll.com"
export LETSENCRYPT_KEY_READER="mqtt-http-bridge"   # matches NODE_APP_USER below

export APACHE_MODE="proxy"
export APACHE_PROXY_RULES="/:8080:/"
export APACHE_PROXY_FLUSH_PATHS="/events"

export NODE_APP_PORT="8080"
export NODE_APP_USER="mqtt-http-bridge"
export NODE_APP_GROUP="mqtt-http-bridge"
export NODE_APP_MAIN_SCRIPT="bin/mqtt-http-bridge.js"
export NODE_APP_DEPLOY_DIRS="src bin"
